"""Produce a complete fabrication package a board house can run directly.

Bundles everything a PCB fab + assembly shop asks for:
  * Gerbers (copper, mask, silk, **paste/stencil**, Edge.Cuts board outline),
  * Excellon drill file,
  * **Pick & Place** (centroid) CSV for assembly,
  * BOM CSV (grouped, with quantities),
  * a fabrication-notes text file (layers, thickness, finish, design rules),
all zipped into ``<name>_fab.zip``.
"""
from __future__ import annotations

import subprocess
import zipfile
from pathlib import Path

from . import bom, kicad_env, route
from .model import Design

FAB_NOTES = """PCB FABRICATION NOTES — {name}
=====================================================
Layers:            2 (top + bottom copper)
Board thickness:   1.6 mm
Copper weight:     1 oz (35 µm)
Surface finish:    HASL (lead-free) or ENIG
Solder mask:       both sides (green standard)
Silkscreen:        both sides (white)
Min track width:   {track} mm
Min clearance:     {clear} mm
Min via:           {via} mm drill / {pad} mm pad
Board outline:     Edge.Cuts layer (see *.gm1 / Edge_Cuts gerber)
Castellated/slots: none

ASSEMBLY
Pick & Place:      {name}-pos.csv  (Ref, Val, Package, PosX, PosY mm, Rot, Side)
BOM:               {name}-bom.csv  (References, Qty, Value, Footprint, Description)
Stencil:           use the *.gtp / *.gbp paste gerbers (top/bottom paste)

Generated by cursor-for-pcb. Gerbers are RS-274X; drill is Excellon.
"""


def _cli(args):
    return subprocess.run([kicad_env.find_cli(), *args],
                          capture_output=True, text=True)


def export_fab(pcb_file: str | Path, design: Design,
               out_dir: str | Path) -> dict:
    """Generate the full fab package. Returns paths + the zip location."""
    pcb_file = Path(pcb_file)
    out = Path(out_dir)
    name = design.name
    gerber_dir = out / "gerbers"
    gerber_dir.mkdir(parents=True, exist_ok=True)

    # 1. Gerbers (all standard fab layers incl. paste for the stencil)
    _cli(["pcb", "export", "gerbers", "--output", str(gerber_dir), str(pcb_file)])
    # 2. Drill (Excellon) + map
    _cli(["pcb", "export", "drill", "--output", str(gerber_dir), str(pcb_file)])
    # 3. Pick & Place centroid CSV (mm)
    pos = out / f"{name}-pos.csv"
    _cli(["pcb", "export", "pos", "--format", "csv", "--units", "mm",
          "--side", "both", "--output", str(pos), str(pcb_file)])
    # 4. BOM
    bom_path = out / f"{name}-bom.csv"
    bom_path.write_text(bom.bom_csv(design))
    # 5. Fab notes
    notes = out / f"{name}-fab-notes.txt"
    notes.write_text(FAB_NOTES.format(
        name=name, track=route.TRACK_W, clear=route.CLEAR_CELLS * route.RES,
        via=route.VIA_DRILL, pad=route.VIA_SIZE))

    # 6. Zip the lot
    zip_path = out / f"{name}_fab.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(gerber_dir.iterdir()):
            z.write(f, f"gerbers/{f.name}")
        for f in (pos, bom_path, notes):
            if f.exists():
                z.write(f, f.name)

    gerbers = sorted(p.name for p in gerber_dir.iterdir())
    return {
        "zip": str(zip_path),
        "gerbers": gerbers,
        "pick_and_place": str(pos),
        "bom": str(bom_path),
        "notes": str(notes),
        "n_gerbers": len(gerbers),
    }
